spring:
  application:
    name: orders-springboot
  cloud:
    stream:
      bindings:
        orders-created:
          binder: kafka
        orders-changes:
          binder: kafka
          group: orders-springboot
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          autoCreateTopics: true
        bindings:
          orders-created:
            producer:
              partitioned: true
              partitionCount: 1
              transacted: true
          orders-changes:
            group: orders-springboot
            consumer:
              autoCommitOffset: true
              enableDlq: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orders_api_2?reWriteBatchedInserts=true
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 30
        connection:
          provider_disables_autocommit: false
        show_sql: true
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
  main:
    allow-bean-definition-overriding: true
server:
  compression:
    enabled: true
