spring:
  application:
    name: orders-springboot
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                username: guest
                password: guest
                port: 5672
                virtual-host: /
      bindings:
        orders-created:
          binder: rabbit
        orders-changes:
          binder: rabbit
          group: orders-springboot
          consumer:
            concurrency: 5
      rabbit:
        bindings:
          orders-created:
            producer:
              transacted: true
          orders-changes:
            binder: rabbit
            group: orders-springboot
            consumer:
              durableSubscription: true
              autoBindDlq: true
              maxConcurrency: 5
#  cloud:
#    stream:
#      instanceCount: 10
#      bindings:
#        orders-created:
#          binder: kafka
#        orders-changes:
#          binder: kafka
#          group: orders-springboot
#      kafka:
#        binder:
#          brokers: localhost
#          defaultBrokerPort: 9092
#          autoCreateTopics: true
#        bindings:
#          orders-created:
#            producer:
#              partitioned: true
#              transacted: true
#          orders-changes:
#            group: orders-springboot
#            consumer:
#              autoCommitOffset: true
#              enableDlq: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orders_api_2?reWriteBatchedInserts=true
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 40
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 30
        connection:
          provider_disables_autocommit: false
        show_sql: true
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
  main:
    allow-bean-definition-overriding: true
server:
  compression:
    enabled: true
